name: Daily Proxy Update

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 01:00 UTC（北京时间 09:00）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run the script
        run: python auto_proxy_subscription.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add clash_sub.yaml
          git commit -m "Update clash_sub.yaml [bot auto]"
          git push